// Generated by CoffeeScript 1.6.1
(function() {
  var a, b, copy, log;

  copy = require('../copyjs');

  log = console.log;

  log('');

  a = 5;

  b = copy(a);

  log('a = 5, b = copy a');

  log('  number a,b', a, b);

  b = 10;

  log('  b=10');

  log('  number a,b', a, b);

  log('');

  a = 'five';

  b = copy(a);

  log("a = 'five', b = copy a");

  log('  string a,b', a, b);

  b = 'twenty';

  log("  b='twenty'");

  log('  string a,b', a, b);

  log('');

  a = new Date();

  b = copy(a);

  log("a = new Date(), b = copy a");

  b = new Date(1974, 4, 22, 4, 44);

  log('  b = new Date(1974, 4, 22, 4, 44)');

  log('  Date a,b', a, b);

  log('');

  a = /cheese/i;

  b = copy(a);

  log("a = /cheese/i, b = copy a");

  log('  Regexp a,b', a, b, "a.test('cheese')", a.test('cheese'), "b.test('cheese')", b.test('cheese'));

  b = /wine/i;

  log('  b=/wine/i');

  log('  Regexp a,b', a, b, "a.test('cheese')", a.test('cheese'), "b.test('WINE')", b.test('WINE'));

  log('');

  a = {
    val: 15,
    business: 'isGood'
  };

  b = copy(a);

  log("a = { val: 15, business:'isGood' }, b = copy a");

  log('  object a,b', a, b);

  b.val = 8000;

  b.business = 'isBetter';

  log('  object a,b', a, b);

  log('');

}).call(this);
