// Generated by CoffeeScript 1.6.1
(function() {
  var copy;

  copy = function(obj) {
    var dest, flags, k;
    if (obj == null) {
      return obj;
    } else if (obj instanceof Date) {
      return new Date(obj.getTime());
    } else if (obj instanceof RegExp) {
      flags = '';
      if (obj.global != null) {
        flags += 'g';
      }
      if (obj.ignoreCase != null) {
        flags += 'i';
      }
      if (obj.multiline != null) {
        flags += 'm';
      }
      if (obj.sticky != null) {
        flags += 'y';
      }
      return new RegExp(obj.source, flags);
    } else if (typeof obj === 'object') {
      dest = obj.constructor();
      for (k in obj) {
        dest[k] = copy(obj[k]);
      }
      return dest;
    } else {
      return JSON.parse(JSON.stringify(obj));
    }
  };

  module.exports = copy;

}).call(this);
