// Generated by CoffeeScript 1.7.1
(function() {
  var copy;

  copy = function(obj) {
    var dest, flags, k;
    if (obj == null) {
      return obj;
    } else {
      switch (true) {
        case obj instanceof Date:
          return new Date(obj.getTime());
        case obj instanceof RegExp:
          flags = '';
          if (obj.global != null) {
            flags += 'g';
          }
          if (obj.ignoreCase != null) {
            flags += 'i';
          }
          if (obj.multiline != null) {
            flags += 'm';
          }
          if (obj.sticky != null) {
            flags += 'y';
          }
          return new RegExp(obj.source, flags);
        case obj instanceof Uint8Array:
        case obj instanceof Uint8ClampedArray:
        case obj instanceof Uint16Array:
        case obj instanceof Uint32Array:
        case obj instanceof Int8Array:
        case obj instanceof Int16Array:
        case obj instanceof Int32Array:
        case obj instanceof Float32Array:
        case obj instanceof Float64Array:
          return obj.subarray();
        case typeof obj === 'object':
          dest = obj.constructor();
          for (k in obj) {
            dest[k] = copy(obj[k]);
          }
          return dest;
        default:
          return JSON.parse(JSON.stringify(obj));
      }
    }
  };

  module.exports = copy;

}).call(this);
